apiVersion: v1
kind: PersistentVolume
metadata:
  name: dragalia-api-aspnet-logs-persisent-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: dragalia-api-aspnet-logs-persisent-volume-claim
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/dragalia-logs"