apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dragalia-api-aspnet-cert-persisent-volume-claim
spec:
  volumeName: dragalia-api-aspnet-cert-persisent-volume
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi