apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dragalia-api-aspnet-log-persistent-volume-claim
spec:
  volumeName: dragalia-api-aspnet-log-persistent-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi