apiVersion: v1
kind: Service
metadata:
  name: dragalia-api-aspnet-service
spec:
  type: ClusterIP
  selector:
    app: dragalia-api-aspnet
  ports:
    - name: "http"
      protocol: TCP
      port: 5000
      targetPort: 80