apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dragalia-api-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              service:
                name: dragalia-api-aspnet-service
                port: 
                  number: 5000