apiVersion: v1
kind: PersistentVolume
metadata:
  name: dragalia-api-postgres-data-persisent-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: dragalia-api-postgres-data-persisent-volume-claim
  storageClassName: manual
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/dragalia-api/db"