apiVersion: apps/v1
kind: Deployment
metadata:
  name: dragalia-api-db
spec:
  selector:
    matchLabels:
      app: dragalia-api-db
  replicas: 1
  template:
    metadata:
      labels:
        app: dragalia-api-db
    spec:
      containers:
        - name: dragalia-api-db
          image: postgres:13
          ports:
            - containerPort: 5432
              name: "postgres"
          volumeMounts:
            - mountPath: '/var/lib/postgresql/data'
              name: dragalia-api-postgres-data-storage
          env:
            - name: POSTGRES_USER
              value: alberius
            - name: POSTGRES_PASSWORD
              value: midgardsormr
      volumes:
        - name: dragalia-api-postgres-data-storage
          persistentVolumeClaim:
            claimName: dragalia-api-postgres-data-persisent-volume-claim