apiVersion: v1
kind: Service
metadata:
  name: dragalia-api-db-service
spec:
  type: ClusterIP
  selector:
    app: dragalia-api-db
  ports:
    - name: "postgres"
      protocol: TCP
      port: 5432
      targetPort: 5432