apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dragalia-api-postgres-data-persisent-volume-claim
spec:
  volumeName: dragalia-api-postgres-data-persisent-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi