apiVersion: apps/v1
kind: Deployment
metadata:
  name: dragalia-api-db
spec:
  selector:
    matchLabels:
      app: dragalia-api-db
  replicas: 1
  template:
    metadata:
      labels:
        app: dragalia-api-db
    spec:
      hostname: postgres
      containers:
        - name: dragalia-api-db
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: "postgres"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: dragalia-api-postgres-data-storage
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: username
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password
                  optional: false
      volumes:
        - name: dragalia-api-postgres-data-storage
          persistentVolumeClaim:
            claimName: dragalia-api-postgres-data-persistent-volume-claim